
package me.arrhioui;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://ws.arrhioui.me/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion", targetNamespace = "http://ws.arrhioui.me/", className = "me.arrhioui.Conversion")
    @ResponseWrapper(localName = "conversionResponse", targetNamespace = "http://ws.arrhioui.me/", className = "me.arrhioui.ConversionResponse")
    @Action(input = "http://ws.arrhioui.me/BankService/conversionRequest", output = "http://ws.arrhioui.me/BankService/conversionResponse")
    public double conversion(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns me.arrhioui.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws.arrhioui.me/", className = "me.arrhioui.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws.arrhioui.me/", className = "me.arrhioui.GetCompteResponse")
    @Action(input = "http://ws.arrhioui.me/BankService/getCompteRequest", output = "http://ws.arrhioui.me/BankService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

}
