
package me.arrhioui;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "se", targetNamespace = "http://ws.arrhioui.me/", wsdlLocation = "http://localhost:8082/BankService?wsdl")
public class Se
    extends Service
{

    private final static URL SE_WSDL_LOCATION;
    private final static WebServiceException SE_EXCEPTION;
    private final static QName SE_QNAME = new QName("http://ws.arrhioui.me/", "se");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/BankService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SE_WSDL_LOCATION = url;
        SE_EXCEPTION = e;
    }

    public Se() {
        super(__getWsdlLocation(), SE_QNAME);
    }

    public Se(WebServiceFeature... features) {
        super(__getWsdlLocation(), SE_QNAME, features);
    }

    public Se(URL wsdlLocation) {
        super(wsdlLocation, SE_QNAME);
    }

    public Se(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SE_QNAME, features);
    }

    public Se(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Se(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "BankServicePort")
    public BankService getBankServicePort() {
        return super.getPort(new QName("http://ws.arrhioui.me/", "BankServicePort"), BankService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "BankServicePort")
    public BankService getBankServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.arrhioui.me/", "BankServicePort"), BankService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SE_EXCEPTION!= null) {
            throw SE_EXCEPTION;
        }
        return SE_WSDL_LOCATION;
    }

}
